export default {
  emptyName: 'Please enter name',
  emptyEmail: 'Email is required',
  invalidEmail: 'Please enter valid email',
  emptyPhoneNo: 'Please enter Phone No',
  invalidPhoneNo: 'Please enter valid Phone No.',
  invalidAlterPhoneNo: 'Please enter valid alternative phone No.',
  alterEmptyPhoneNo: 'Please enter alternative Phone No',
  alterInvalidPhoneNo:
    'Alternate phone number must be different from phone num',
  emptyPassword: 'Please enter Password',
  emptyConfirmPassword: 'Please enter Confirm Password',
  notSamePassword: 'Password and Confirm Password must be same',
  invalidPassword:
    'Password must have 8 characters, include an uppercase, a number, and a special character latter',
  emptyFirstName: 'Please enter First Name',
  emptyLastName: 'Please enter Last Name',
  emptyDOB: 'Please select DOB',
  emptyGender: 'Please select Gender',
  emptyQualification: 'Please enter Qualification',
  emptyOTP: 'Verification Code is required',
  invalidOTP: 'Please enter valid Verification Code',
  emptyState: 'Please select State',
  emptyDistrict: 'Please select District',
  emptySubject: 'Please enter subject',
  emptyMessage: 'Please enter message',
  invalidMessageLength: 'Please enter minimum 10 words',
};
